version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run ESLint
          command: npm run lint
workflows:
  version: 2
  build:
    jobs:
      - build
